/**
 * Generates a throwaway certificate chain so the Apple Wallet flow can be run
 * end to end on a laptop — the "Add to Apple Wallet" button appears, the
 * .pkpass is built and signed, and the pass web service works.
 *
 * The passes it signs are NOT trusted by iOS: a real iPhone refuses to install
 * them. Use this to develop and demo the flow, and replace the values with your
 * Apple certificates (see docs/WALLET.md) before putting it in front of
 * customers.
 *
 *   npx tsx scripts/dev-wallet-certs.ts          # print the variables
 *   npx tsx scripts/dev-wallet-certs.ts --write  # append them to apps/api/.env
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import forge from 'node-forge';

const PASS_TYPE_IDENTIFIER = 'pass.dev.loyaltyapp.local';
const TEAM_IDENTIFIER = 'DEVTEAM123';

function selfSigned(commonName: string) {
  const keys = forge.pki.rsa.generateKeyPair(2048);
  const cert = forge.pki.createCertificate();
  cert.publicKey = keys.publicKey;
  cert.serialNumber = '01';
  cert.validity.notBefore = new Date();
  cert.validity.notAfter = new Date(Date.now() + 365 * 86_400_000);
  const attrs = [{ name: 'commonName', value: commonName }];
  cert.setSubject(attrs);
  cert.setIssuer(attrs);
  cert.sign(keys.privateKey, forge.md.sha256.create());
  return {
    cert: forge.pki.certificateToPem(cert),
    key: forge.pki.privateKeyToPem(keys.privateKey),
  };
}

const pass = selfSigned(`Pass Type ID: ${PASS_TYPE_IDENTIFIER}`);
const wwdr = selfSigned('Development WWDR (not Apple)');

const oneLine = (pem: string) => pem.replace(/\r?\n/g, '\\n');

const block = `
# --- Development-only Apple Wallet certificates -----------------------------
# Generated by scripts/dev-wallet-certs.ts. iOS will NOT install passes signed
# with these; replace them with your Apple certificates before going live.
APPLE_PASS_TYPE_IDENTIFIER=${PASS_TYPE_IDENTIFIER}
APPLE_TEAM_IDENTIFIER=${TEAM_IDENTIFIER}
APPLE_APNS_TOPIC=${PASS_TYPE_IDENTIFIER}
APPLE_PASS_CERT_PEM="${oneLine(pass.cert)}"
APPLE_PASS_KEY_PEM="${oneLine(pass.key)}"
APPLE_WWDR_CERT_PEM="${oneLine(wwdr.cert)}"
`;

if (process.argv.includes('--write')) {
  const envPath = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '.env');
  const current = fs.existsSync(envPath) ? fs.readFileSync(envPath, 'utf8') : '';
  if (current.includes('APPLE_PASS_CERT_PEM')) {
    console.error('apps/api/.env already defines APPLE_PASS_CERT_PEM — remove it first.');
    process.exit(1);
  }
  fs.appendFileSync(envPath, block);
  console.log('Development Apple Wallet certificates written to apps/api/.env');
  console.log('Restart the API, and the "Add to Apple Wallet" button appears on the join page.');
} else {
  console.log(block);
  console.log('# Re-run with --write to append these to apps/api/.env');
}
